build: off

install:
  - ps: iex (iwr https://deno.land/x/install/install.ps1)
  
before_test:
  - start_db.sh

test_script: 
  - set ACCESS_KEY_ID=fraud
  - set SECRET_ACCESS_KEY=fraud
  - deno run --allow-read --allow-env --allow-net ./test.ts